package ai.basic.x1.adapter.dto;

import com.fasterxml.jackson.annotation.JsonTypeName;
import lombok.Data;

/**
 * @author Jagger Wang
 */
@Data
@JsonTypeName("pcdFile")
public class PcdFileDTO extends FileDTO {

    /**
     * Pcd binary file object
     */
    private FileDTO binary;

    /**
     * Pcd binary compressed file object
     */
    private FileDTO binaryCompressed;

    /**
     * Low-density binary PCD preview, when generated by pcd-tools.
     */
    private FileDTO preview;

    /** Optional spatial chunk manifest for large point clouds. */
    private FileDTO chunkManifest;

    /**
     * Pcd render image file object
     */
    private FileDTO renderImage;
}
