
CAMERA_SURROUND_FRONT = 0
CAMERA_SURROUND_LEFT = 1
CAMERA_SURROUND_BACK = 2
CAMERA_SURROUND_RIGHT = 3
CAMERA_FRONT_NEAR = 4
CAMERA_FRONT_MIDDLE = 5
CAMERA_FRONT_FAR = 6

CAMERA_STITCHED = 100
CAMERA_STITCHED_NEAR = 101
CAMERA_STITCHED_NEAR_CROP = 102
