auto_scale_lr = dict(base_batch_size=32, enable=False)
backend_args = None
camera_calibrations = [
    dict(
        axis_signs=[
            1.0,
            -1.0,
            -1.0,
        ],
        camera_intrinsic=[
            [
                317.01254197439897,
                0.0,
                663.4047748335187,
            ],
            [
                0.0,
                317.0023758803889,
                326.0984106866462,
            ],
            [
                0.0,
                0.0,
                1.0,
            ],
        ],
        camera_model='fisheye',
        camera_name='CAM_FRONT',
        distortion=[
            0.08167513010016911,
            0.03127473950834274,
            -0.019971375474817647,
            0.0023991777601088528,
        ]),
    dict(
        axis_signs=[
            1.0,
            -1.0,
            -1.0,
        ],
        camera_intrinsic=[
            [
                319.39,
                0.0,
                641.912,
            ],
            [
                0.0,
                319.459,
                323.807,
            ],
            [
                0.0,
                0.0,
                1.0,
            ],
        ],
        camera_model='fisheye',
        camera_name='CAM_LEFT',
        distortion=[
            0.0772143,
            0.0373292,
            -0.021348,
            0.0022813,
        ]),
    dict(
        axis_signs=[
            1.0,
            -1.0,
            -1.0,
        ],
        camera_intrinsic=[
            [
                316.04215020904763,
                0.0,
                657.8146280065309,
            ],
            [
                0.0,
                316.11328528450775,
                344.8465437212912,
            ],
            [
                0.0,
                0.0,
                1.0,
            ],
        ],
        camera_model='fisheye',
        camera_name='CAM_BACK',
        distortion=[
            0.07865616805982469,
            0.03161245031273102,
            -0.019612367256880002,
            0.0023425362039370423,
        ]),
    dict(
        axis_signs=[
            1.0,
            -1.0,
            -1.0,
        ],
        camera_intrinsic=[
            [
                320.606,
                0.0,
                642.637,
            ],
            [
                0.0,
                320.311,
                348.676,
            ],
            [
                0.0,
                0.0,
                1.0,
            ],
        ],
        camera_model='fisheye',
        camera_name='CAM_RIGHT',
        distortion=[
            0.0752761,
            0.038262,
            -0.0224308,
            0.00248036,
        ]),
]
class_names = [
    'Car',
    'Cone',
    'Pillar',
]
custom_hooks = [
    dict(disable_after_epoch=15, type='DisableObjectSampleHook'),
]
custom_imports = dict(
    allow_failed_imports=False, imports=[
        'projects.BEVFusion.bevfusion',
    ])
data_prefix = dict(
    CAM_BACK='samples/CAM_BACK',
    CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
    CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
    CAM_FRONT='samples/CAM_FRONT',
    CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
    CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
    CAM_LEFT='samples/CAM_LEFT',
    CAM_RIGHT='samples/CAM_RIGHT',
    pts='samples/LIDAR_TOP_BIN',
    sweeps='sweeps/LIDAR_TOP_BIN')
data_root = 'data/nuscenes/'
dataset_type = 'CustomNuScenesThreeClassDataset'
db_sampler = dict(
    classes=[
        'Car',
        'Cone',
        'Pillar',
    ],
    data_root='data/nuscenes/',
    info_path='data/nuscenes/nuscenes_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(Car=3, Cone=5, Pillar=3)),
    rate=1.0,
    sample_groups=dict(Car=2, Cone=3, Pillar=2))
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
image_bot_pct_lim = [
    0.35,
    0.5,
]
image_resize_lim = [
    0.58,
    0.72,
]
image_val_bot_pct = 0.42
image_val_resize = 0.65
input_modality = dict(use_camera=True, use_lidar=True)
launcher = 'pytorch'
load_from = '/PnP/lxzhu/mmdetection3d/work_dirs/bevfusion_lidar_custom_nus_3class/epoch_20.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
lr = 5e-05
metainfo = dict(
    box_type_3d='LiDAR', classes=[
        'Car',
        'Cone',
        'Pillar',
    ])
model = dict(
    bbox_head=dict(
        auxiliary=True,
        bbox_coder=dict(
            code_size=10,
            out_size_factor=8,
            pc_range=[
                -21.0,
                -21.0,
            ],
            post_center_range=[
                -21.0,
                -21.0,
                -5.0,
                21.0,
                21.0,
                4.0,
            ],
            score_threshold=0.0,
            type='TransFusionBBoxCoder',
            voxel_size=[
                0.075,
                0.075,
            ]),
        bn_momentum=0.1,
        common_heads=dict(
            center=[
                2,
                2,
            ],
            dim=[
                3,
                2,
            ],
            height=[
                1,
                2,
            ],
            rot=[
                2,
                2,
            ],
            vel=[
                2,
                2,
            ]),
        decoder_layer=dict(
            cross_attn_cfg=dict(dropout=0.1, embed_dims=128, num_heads=8),
            ffn_cfg=dict(
                act_cfg=dict(inplace=True, type='ReLU'),
                embed_dims=128,
                feedforward_channels=256,
                ffn_drop=0.1,
                num_fcs=2),
            norm_cfg=dict(type='LN'),
            pos_encoding_cfg=dict(input_channel=2, num_pos_feats=128),
            self_attn_cfg=dict(dropout=0.1, embed_dims=128, num_heads=8),
            type='TransformerDecoderLayer'),
        hidden_channel=128,
        in_channels=512,
        loss_bbox=dict(
            loss_weight=0.25, reduction='mean', type='mmdet.L1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            reduction='mean',
            type='mmdet.FocalLoss',
            use_sigmoid=True),
        loss_heatmap=dict(
            loss_weight=1.0, reduction='mean', type='mmdet.GaussianFocalLoss'),
        nms_kernel_size=3,
        num_classes=3,
        num_decoder_layers=1,
        num_proposals=200,
        test_cfg=dict(
            dataset='custom',
            grid_size=[
                560,
                560,
                46,
            ],
            nms_type=None,
            out_size_factor=8,
            pc_range=[
                -21.0,
                -21.0,
            ],
            voxel_size=[
                0.075,
                0.075,
            ]),
        train_cfg=dict(
            assigner=dict(
                cls_cost=dict(
                    alpha=0.25,
                    gamma=2.0,
                    type='mmdet.FocalLossCost',
                    weight=0.15),
                iou_calculator=dict(coordinate='lidar', type='BboxOverlaps3D'),
                iou_cost=dict(type='IoU3DCost', weight=0.25),
                reg_cost=dict(type='BBoxBEVL1Cost', weight=0.25),
                type='HungarianAssigner3D'),
            code_weights=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.0,
                0.0,
            ],
            dataset='custom',
            gaussian_overlap=0.1,
            grid_size=[
                560,
                560,
                46,
            ],
            min_radius=1,
            out_size_factor=8,
            point_cloud_range=[
                -21.0,
                -21.0,
                -5.0,
                21.0,
                21.0,
                4.0,
            ],
            pos_weight=-1,
            voxel_size=[
                0.075,
                0.075,
                0.2,
            ]),
        type='TransFusionHead'),
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='Det3DDataPreprocessor',
        voxelize_cfg=dict(
            max_num_points=10,
            max_voxels=[
                120000,
                160000,
            ],
            point_cloud_range=[
                -21.0,
                -21.0,
                -5.0,
                21.0,
                21.0,
                4.0,
            ],
            voxel_size=[
                0.075,
                0.075,
                0.2,
            ],
            voxelize_reduce=True)),
    fusion_layer=dict(
        in_channels=[
            80,
            256,
        ], out_channels=256, type='ConvFuser'),
    img_backbone=dict(
        attn_drop_rate=0.0,
        convert_weights=True,
        depths=[
            2,
            2,
            6,
            2,
        ],
        drop_path_rate=0.2,
        drop_rate=0.0,
        embed_dims=96,
        init_cfg=None,
        mlp_ratio=4,
        num_heads=[
            3,
            6,
            12,
            24,
        ],
        out_indices=[
            1,
            2,
            3,
        ],
        patch_norm=True,
        qk_scale=None,
        qkv_bias=True,
        type='mmdet.SwinTransformer',
        window_size=7,
        with_cp=False),
    img_neck=dict(
        act_cfg=dict(inplace=True, type='ReLU'),
        in_channels=[
            192,
            384,
            768,
        ],
        norm_cfg=dict(requires_grad=True, type='BN2d'),
        num_outs=3,
        out_channels=256,
        start_level=0,
        type='GeneralizedLSSFPN',
        upsample_cfg=dict(align_corners=False, mode='bilinear')),
    pts_backbone=dict(
        conv_cfg=dict(bias=False, type='Conv2d'),
        in_channels=256,
        layer_nums=[
            5,
            5,
        ],
        layer_strides=[
            1,
            2,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            128,
            256,
        ],
        type='SECOND'),
    pts_middle_encoder=dict(
        block_type='basicblock',
        encoder_channels=(
            (
                16,
                16,
                32,
            ),
            (
                32,
                32,
                64,
            ),
            (
                64,
                64,
                128,
            ),
            (
                128,
                128,
            ),
        ),
        encoder_paddings=(
            (
                0,
                0,
                1,
            ),
            (
                0,
                0,
                1,
            ),
            (
                0,
                0,
                (
                    1,
                    1,
                    0,
                ),
            ),
            (
                0,
                0,
            ),
        ),
        in_channels=5,
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN1d'),
        order=(
            'conv',
            'norm',
            'act',
        ),
        sparse_shape=[
            560,
            560,
            46,
        ],
        type='BEVFusionSparseEncoder'),
    pts_neck=dict(
        in_channels=[
            128,
            256,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            256,
            256,
        ],
        type='SECONDFPN',
        upsample_cfg=dict(bias=False, type='deconv'),
        upsample_strides=[
            1,
            2,
        ],
        use_conv_for_no_stride=True),
    pts_voxel_encoder=dict(num_features=5, type='HardSimpleVFE'),
    type='BEVFusion',
    view_transform=dict(
        camera_calibrations=[
            dict(
                axis_signs=[
                    1.0,
                    -1.0,
                    -1.0,
                ],
                camera_intrinsic=[
                    [
                        317.01254197439897,
                        0.0,
                        663.4047748335187,
                    ],
                    [
                        0.0,
                        317.0023758803889,
                        326.0984106866462,
                    ],
                    [
                        0.0,
                        0.0,
                        1.0,
                    ],
                ],
                camera_model='fisheye',
                camera_name='CAM_FRONT',
                distortion=[
                    0.08167513010016911,
                    0.03127473950834274,
                    -0.019971375474817647,
                    0.0023991777601088528,
                ]),
            dict(
                axis_signs=[
                    1.0,
                    -1.0,
                    -1.0,
                ],
                camera_intrinsic=[
                    [
                        319.39,
                        0.0,
                        641.912,
                    ],
                    [
                        0.0,
                        319.459,
                        323.807,
                    ],
                    [
                        0.0,
                        0.0,
                        1.0,
                    ],
                ],
                camera_model='fisheye',
                camera_name='CAM_LEFT',
                distortion=[
                    0.0772143,
                    0.0373292,
                    -0.021348,
                    0.0022813,
                ]),
            dict(
                axis_signs=[
                    1.0,
                    -1.0,
                    -1.0,
                ],
                camera_intrinsic=[
                    [
                        316.04215020904763,
                        0.0,
                        657.8146280065309,
                    ],
                    [
                        0.0,
                        316.11328528450775,
                        344.8465437212912,
                    ],
                    [
                        0.0,
                        0.0,
                        1.0,
                    ],
                ],
                camera_model='fisheye',
                camera_name='CAM_BACK',
                distortion=[
                    0.07865616805982469,
                    0.03161245031273102,
                    -0.019612367256880002,
                    0.0023425362039370423,
                ]),
            dict(
                axis_signs=[
                    1.0,
                    -1.0,
                    -1.0,
                ],
                camera_intrinsic=[
                    [
                        320.606,
                        0.0,
                        642.637,
                    ],
                    [
                        0.0,
                        320.311,
                        348.676,
                    ],
                    [
                        0.0,
                        0.0,
                        1.0,
                    ],
                ],
                camera_model='fisheye',
                camera_name='CAM_RIGHT',
                distortion=[
                    0.0752761,
                    0.038262,
                    -0.0224308,
                    0.00248036,
                ]),
        ],
        dbound=[
            1.0,
            30.0,
            0.5,
        ],
        downsample=2,
        feature_size=[
            32,
            88,
        ],
        image_size=[
            256,
            704,
        ],
        in_channels=256,
        out_channels=80,
        type='DepthLSSTransform',
        xbound=[
            -21.0,
            21.0,
            0.3,
        ],
        ybound=[
            -21.0,
            21.0,
            0.3,
        ],
        zbound=[
            -5.0,
            4.0,
            9.0,
        ]))
object_sampler = dict(
    classes=[
        'Car',
        'Cone',
        'Pillar',
    ],
    data_root='data/nuscenes/',
    info_path='data/nuscenes/nuscenes_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(Car=3, Cone=5, Pillar=3)),
    rate=1.0,
    sample_groups=dict(Car=2, Cone=3, Pillar=2))
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    loss_scale='dynamic',
    optimizer=dict(lr=5e-05, type='AdamW', weight_decay=0.01),
    type='AmpOptimWrapper')
param_scheduler = [
    dict(
        T_max=8,
        begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=8,
        eta_min=0.0005,
        type='CosineAnnealingLR'),
    dict(
        T_max=12,
        begin=8,
        by_epoch=True,
        convert_to_iter_based=True,
        end=20,
        eta_min=5e-09,
        type='CosineAnnealingLR'),
    dict(
        T_max=8,
        begin=0,
        by_epoch=True,
        convert_to_iter_based=True,
        end=8,
        eta_min=0.8947368421052632,
        type='CosineAnnealingMomentum'),
    dict(
        T_max=12,
        begin=8,
        by_epoch=True,
        convert_to_iter_based=True,
        end=20,
        eta_min=1,
        type='CosineAnnealingMomentum'),
]
point_cloud_range = [
    -21.0,
    -21.0,
    -5.0,
    21.0,
    21.0,
    4.0,
]
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_test_bin.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_LEFT='samples/CAM_LEFT',
            CAM_RIGHT='samples/CAM_RIGHT',
            pts='samples/LIDAR_TOP_BIN',
            sweeps='sweeps/LIDAR_TOP_BIN'),
        data_root='data/nuscenes/',
        metainfo=dict(
            box_type_3d='LiDAR', classes=[
                'Car',
                'Cone',
                'Pillar',
            ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                color_type='color',
                num_views=4,
                to_float32=True,
                type='BEVLoadMultiViewImageFromFiles'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                load_dim=5,
                pad_empty_sweeps=True,
                remove_close=True,
                sweeps_num=5,
                test_mode=True,
                type='LoadPointsFromMultiSweeps',
                use_dim=5),
            dict(
                blind_zone_front=1.3,
                blind_zone_rear=1.3,
                car_config_path='/models/car.json',
                type='FilterVehicleBlindZone'),
            dict(
                bot_pct_lim=[
                    0.42,
                    0.42,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.65,
                    0.65,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                point_cloud_range=[
                    -21.0,
                    -21.0,
                    -5.0,
                    21.0,
                    21.0,
                    4.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'img',
                    'points',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='CustomNuScenesThreeClassDataset',
        use_valid_flag=False,
        with_velocity=False),
    drop_last=False,
    num_workers=1,
    persistent_workers=False,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    collect_device='cpu', iou_thr=[
        0.25,
        0.5,
        0.7,
    ], type='IndoorMetric')
test_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        num_views=4,
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        load_dim=5,
        pad_empty_sweeps=True,
        remove_close=True,
        sweeps_num=5,
        test_mode=True,
        type='LoadPointsFromMultiSweeps',
        use_dim=5),
    dict(
        blind_zone_front=1.3,
        blind_zone_rear=1.3,
        car_config_path='/models/car.json',
        type='FilterVehicleBlindZone'),
    dict(
        bot_pct_lim=[
            0.42,
            0.42,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.65,
            0.65,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        point_cloud_range=[
            -21.0,
            -21.0,
            -5.0,
            21.0,
            21.0,
            4.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'img',
            'points',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'num_pts_feats',
        ],
        type='Pack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=20, val_interval=5)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        dataset=dict(
            ann_file='nuscenes_infos_train_bin.pkl',
            backend_args=None,
            box_type_3d='LiDAR',
            data_prefix=dict(
                CAM_BACK='samples/CAM_BACK',
                CAM_BACK_LEFT='samples/CAM_BACK_LEFT',
                CAM_BACK_RIGHT='samples/CAM_BACK_RIGHT',
                CAM_FRONT='samples/CAM_FRONT',
                CAM_FRONT_LEFT='samples/CAM_FRONT_LEFT',
                CAM_FRONT_RIGHT='samples/CAM_FRONT_RIGHT',
                CAM_LEFT='samples/CAM_LEFT',
                CAM_RIGHT='samples/CAM_RIGHT',
                pts='samples/LIDAR_TOP_BIN',
                sweeps='sweeps/LIDAR_TOP_BIN'),
            data_root='data/nuscenes/',
            metainfo=dict(
                box_type_3d='LiDAR', classes=[
                    'Car',
                    'Cone',
                    'Pillar',
                ]),
            modality=dict(use_camera=True, use_lidar=True),
            pipeline=[
                dict(
                    backend_args=None,
                    color_type='color',
                    num_views=4,
                    to_float32=True,
                    type='BEVLoadMultiViewImageFromFiles'),
                dict(
                    backend_args=None,
                    coord_type='LIDAR',
                    load_dim=5,
                    type='LoadPointsFromFile',
                    use_dim=5),
                dict(
                    backend_args=None,
                    load_dim=5,
                    pad_empty_sweeps=True,
                    remove_close=True,
                    sweeps_num=5,
                    type='LoadPointsFromMultiSweeps',
                    use_dim=5),
                dict(
                    blind_zone_front=1.3,
                    blind_zone_rear=1.3,
                    car_config_path='/models/car.json',
                    type='FilterVehicleBlindZone'),
                dict(
                    type='LoadAnnotations3D',
                    with_attr_label=False,
                    with_bbox_3d=True,
                    with_label_3d=True),
                dict(
                    db_sampler=dict(
                        classes=[
                            'Car',
                            'Cone',
                            'Pillar',
                        ],
                        data_root='data/nuscenes/',
                        info_path='data/nuscenes/nuscenes_dbinfos_train.pkl',
                        points_loader=dict(
                            backend_args=None,
                            coord_type='LIDAR',
                            load_dim=5,
                            type='LoadPointsFromFile',
                            use_dim=[
                                0,
                                1,
                                2,
                                3,
                                4,
                            ]),
                        prepare=dict(
                            filter_by_difficulty=[
                                -1,
                            ],
                            filter_by_min_points=dict(Car=3, Cone=5,
                                                      Pillar=3)),
                        rate=1.0,
                        sample_groups=dict(Car=2, Cone=3, Pillar=2)),
                    type='ObjectSample'),
                dict(
                    bot_pct_lim=[
                        0.35,
                        0.5,
                    ],
                    final_dim=[
                        256,
                        704,
                    ],
                    is_train=True,
                    rand_flip=True,
                    resize_lim=[
                        0.58,
                        0.72,
                    ],
                    rot_lim=[
                        -5.4,
                        5.4,
                    ],
                    type='ImageAug3D'),
                dict(
                    rot_range=[
                        -0.78539816,
                        0.78539816,
                    ],
                    scale_ratio_range=[
                        0.9,
                        1.1,
                    ],
                    translation_std=0.5,
                    type='BEVFusionGlobalRotScaleTrans'),
                dict(type='BEVFusionRandomFlip3D'),
                dict(
                    point_cloud_range=[
                        -21.0,
                        -21.0,
                        -5.0,
                        21.0,
                        21.0,
                        4.0,
                    ],
                    type='PointsRangeFilter'),
                dict(
                    point_cloud_range=[
                        -21.0,
                        -21.0,
                        -5.0,
                        21.0,
                        21.0,
                        4.0,
                    ],
                    type='ObjectRangeFilter'),
                dict(
                    classes=[
                        'Car',
                        'Cone',
                        'Pillar',
                    ],
                    type='ObjectNameFilter'),
                dict(min_num_points=1, type='FilterBoxesWithoutPoints'),
                dict(
                    fixed_prob=True,
                    max_epoch=6,
                    mode=1,
                    offset=False,
                    prob=0.0,
                    ratio=0.5,
                    rotate=1,
                    type='GridMask',
                    use_h=True,
                    use_w=True),
                dict(type='PointShuffle'),
                dict(
                    keys=[
                        'points',
                        'img',
                        'gt_bboxes_3d',
                        'gt_labels_3d',
                        'gt_bboxes',
                        'gt_labels',
                    ],
                    meta_keys=[
                        'cam2img',
                        'ori_cam2img',
                        'lidar2cam',
                        'lidar2img',
                        'cam2lidar',
                        'ori_lidar2img',
                        'img_aug_matrix',
                        'box_type_3d',
                        'sample_idx',
                        'lidar_path',
                        'img_path',
                        'transformation_3d_flow',
                        'pcd_rotation',
                        'pcd_scale_factor',
                        'pcd_trans',
                        'lidar_aug_matrix',
                        'num_pts_feats',
                    ],
                    type='Pack3DDetInputs'),
            ],
            test_mode=False,
            type='CustomNuScenesThreeClassDataset',
            use_valid_flag=False),
        type='CBGSDataset'),
    num_workers=1,
    persistent_workers=False,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        num_views=4,
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        load_dim=5,
        pad_empty_sweeps=True,
        remove_close=True,
        sweeps_num=5,
        type='LoadPointsFromMultiSweeps',
        use_dim=5),
    dict(
        blind_zone_front=1.3,
        blind_zone_rear=1.3,
        car_config_path='/models/car.json',
        type='FilterVehicleBlindZone'),
    dict(
        type='LoadAnnotations3D',
        with_attr_label=False,
        with_bbox_3d=True,
        with_label_3d=True),
    dict(
        db_sampler=dict(
            classes=[
                'Car',
                'Cone',
                'Pillar',
            ],
            data_root='data/nuscenes/',
            info_path='data/nuscenes/nuscenes_dbinfos_train.pkl',
            points_loader=dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=[
                    0,
                    1,
                    2,
                    3,
                    4,
                ]),
            prepare=dict(
                filter_by_difficulty=[
                    -1,
                ],
                filter_by_min_points=dict(Car=3, Cone=5, Pillar=3)),
            rate=1.0,
            sample_groups=dict(Car=2, Cone=3, Pillar=2)),
        type='ObjectSample'),
    dict(
        bot_pct_lim=[
            0.35,
            0.5,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=True,
        rand_flip=True,
        resize_lim=[
            0.58,
            0.72,
        ],
        rot_lim=[
            -5.4,
            5.4,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            -0.78539816,
            0.78539816,
        ],
        scale_ratio_range=[
            0.9,
            1.1,
        ],
        translation_std=0.5,
        type='BEVFusionGlobalRotScaleTrans'),
    dict(type='BEVFusionRandomFlip3D'),
    dict(
        point_cloud_range=[
            -21.0,
            -21.0,
            -5.0,
            21.0,
            21.0,
            4.0,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            -21.0,
            -21.0,
            -5.0,
            21.0,
            21.0,
            4.0,
        ],
        type='ObjectRangeFilter'),
    dict(classes=[
        'Car',
        'Cone',
        'Pillar',
    ], type='ObjectNameFilter'),
    dict(min_num_points=1, type='FilterBoxesWithoutPoints'),
    dict(
        fixed_prob=True,
        max_epoch=6,
        mode=1,
        offset=False,
        prob=0.0,
        ratio=0.5,
        rotate=1,
        type='GridMask',
        use_h=True,
        use_w=True),
    dict(type='PointShuffle'),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
            'gt_bboxes',
            'gt_labels',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
            'lidar_aug_matrix',
            'num_pts_feats',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='nuscenes_infos_test_bin.pkl',
        backend_args=None,
        box_type_3d='LiDAR',
        data_prefix=dict(
            CAM_BACK='samples/CAM_BACK',
            CAM_FRONT='samples/CAM_FRONT',
            CAM_LEFT='samples/CAM_LEFT',
            CAM_RIGHT='samples/CAM_RIGHT',
            pts='samples/LIDAR_TOP_BIN',
            sweeps='sweeps/LIDAR_TOP_BIN'),
        data_root='data/nuscenes/',
        metainfo=dict(
            box_type_3d='LiDAR', classes=[
                'Car',
                'Cone',
                'Pillar',
            ]),
        modality=dict(use_camera=True, use_lidar=True),
        pipeline=[
            dict(
                backend_args=None,
                color_type='color',
                num_views=4,
                to_float32=True,
                type='BEVLoadMultiViewImageFromFiles'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=5,
                type='LoadPointsFromFile',
                use_dim=5),
            dict(
                backend_args=None,
                load_dim=5,
                pad_empty_sweeps=True,
                remove_close=True,
                sweeps_num=5,
                test_mode=True,
                type='LoadPointsFromMultiSweeps',
                use_dim=5),
            dict(
                blind_zone_front=1.3,
                blind_zone_rear=1.3,
                car_config_path='/models/car.json',
                type='FilterVehicleBlindZone'),
            dict(
                bot_pct_lim=[
                    0.42,
                    0.42,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.65,
                    0.65,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                point_cloud_range=[
                    -21.0,
                    -21.0,
                    -5.0,
                    21.0,
                    21.0,
                    4.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'img',
                    'points',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                meta_keys=[
                    'cam2img',
                    'ori_cam2img',
                    'lidar2cam',
                    'lidar2img',
                    'cam2lidar',
                    'ori_lidar2img',
                    'img_aug_matrix',
                    'box_type_3d',
                    'sample_idx',
                    'lidar_path',
                    'img_path',
                    'num_pts_feats',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='CustomNuScenesThreeClassDataset',
        use_valid_flag=False,
        with_velocity=False),
    drop_last=False,
    num_workers=1,
    persistent_workers=False,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    collect_device='cpu', iou_thr=[
        0.25,
        0.5,
        0.7,
    ], type='IndoorMetric')
val_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        num_views=4,
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        backend_args=None,
        load_dim=5,
        pad_empty_sweeps=True,
        remove_close=True,
        sweeps_num=5,
        test_mode=True,
        type='LoadPointsFromMultiSweeps',
        use_dim=5),
    dict(
        blind_zone_front=1.3,
        blind_zone_rear=1.3,
        car_config_path='/models/car.json',
        type='FilterVehicleBlindZone'),
    dict(
        bot_pct_lim=[
            0.42,
            0.42,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.65,
            0.65,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        point_cloud_range=[
            -21.0,
            -21.0,
            -5.0,
            21.0,
            21.0,
            4.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'img',
            'points',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        meta_keys=[
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'img_aug_matrix',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'num_pts_feats',
        ],
        type='Pack3DDetInputs'),
]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
voxel_size = [
    0.075,
    0.075,
    0.2,
]
work_dir = 'work_dirs/bevfusion_lidar_cam_custom_nus_3class_v2'
