ALTER TABLE `class`
    MODIFY COLUMN `tool_type`
        enum ('POLYGON','BOUNDING_BOX','POLYLINE','KEY_POINT','SEGMENTATION','CUBOID','PARKING_SLOT')
        CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;

ALTER TABLE `dataset_class`
    MODIFY COLUMN `tool_type`
        enum ('POLYGON','BOUNDING_BOX','POLYLINE','KEY_POINT','SEGMENTATION','CUBOID','PARKING_SLOT')
        CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
