ALTER TABLE `file`
    MODIFY COLUMN `relation` enum (
        'LARGE_THUMBTHUMBNAIL',
        'MEDIUM_THUMBTHUMBNAIL',
        'SMALL_THUMBTHUMBNAIL',
        'BINARY',
        'BINARY_COMPRESSED',
        'POINT_CLOUD_PREVIEW',
        'POINT_CLOUD_RENDER_IMAGE'
    ) CHARACTER SET utf8 DEFAULT NULL
    COMMENT 'Relation(LARGE_THUMBTHUMBNAIL,MEDIUM_THUMBTHUMBNAIL,SMALL_THUMBTHUMBNAIL,BINARY,BINARY_COMPRESSED,POINT_CLOUD_PREVIEW,POINT_CLOUD_RENDER_IMAGE)';
